input {
  file {
    path => "/local_data/conn-json_2024-08-27.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

output {
  kafka {
    bootstrap_servers => "kafka:29092"
    topic_id => "test"
    codec => json
  }
}