input {
  file {
    path => "/local_data/conn-json_2024-08-27.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

output {
    rabbitmq {
    host => "${RABBITMQ_HOST}"
    port => "${RABBITMQ_PORT}"
    user => "${RABBITMQ_USER}"
    password => "${RABBITMQ_PASSWORD}"
    exchange => "logstash_exchange"
    exchange_type => "fanout"
    key => "logstash_routing_key"
    durable => true
    persistent => true
  }
}